# Generated by Django 4.2.2 on 2023-06-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0004_section_blog_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Section1',
        ),
    ]
