# Generated by Django 4.2.2 on 2023-06-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0005_rename_section_section1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.DeleteModel(
            name='Section1',
        ),
    ]
