# Generated by Django 4.2.2 on 2023-06-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0008_rename_section1_bheem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bheem',
        ),
    ]
